In [21]:
import pandas as pd #import the pandas and aliasing as pd
import numpy as np

## Series

In [22]:
data = np.array(['a','b','c','d'])
s1 = pd.Series(data)
print(s1)

data = np.array([1,2,3,4])
s2 = pd.Series(data)
print(s2)

0    a
1    b
2    c
3    d
dtype: object
0    1
1    2
2    3
3    4
dtype: int32

### What are the results? What are the differences between s1 and s2?

Ans: s1 is series of string, s2 is series of integer

Now, it is your turn to create an heterogeneously-typed series. For example, [1,‘b’,3,‘d’]. What is a data type of the heterogeneously-typed series
when you print out the created series?
We can also alter the index assigned to elements using the following code

In [4]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print(s)

100    a
101    b
102    c
103    d
dtype: object

In [6]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s[0])

1

### Exercise: Write a code to retrieve (show) only the first three elements in Series s.

In [10]:
s[0:3]

a    1
b    2
c    3
dtype: int64

In [16]:
s.values[0:3]

array([1, 2, 3], dtype=int64)

### Exercise: Let try to use an index (e.g. ‘a’) to access the element in Series s, e.g. s[[‘a’]]

In [18]:
s[["a"]]

a    1
dtype: int64

In [20]:
s[["a", "c", "d"]]

a    1
c    3
d    4
dtype: int64

## Dataframe

In [24]:
data = [1,2,3,4,5]
df1 = pd.DataFrame(data)
print(df1)
data = [['Alex',10],['Bob',12],['Clarke',13]]
df2 = pd.DataFrame(data,columns=['Name','Age'])
print(df2)

   0
0  1
1  2
2  3
3  4
4  5
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

### Create a DataFrame from Dict of Series

In [25]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'
])}
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

### Notice that we have NaN, why?

NaN exists in this dataframe because one's d is not defined by user.

### Exercise: now, this is your turn to create the following table as Dataframe and name this table as studentDF.

In [42]:
d = {"Math" : [90, 10, 34, 23, 43],
     "C_programming" : [70, 20, 25, 32, 73],
     "Java" : [50, 41, 67, 34, 23 ],
     "Web_programming" : [55, 66, 23, 76, 67]}
student_df = pd.DataFrame(d)
student_df

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23
3    23             32    34               76
4    43             73    23               67

In [34]:
print(df, end="\n\n")
print(df[2:4], end="\n\n") #Slice Rows
print(df.loc[0], end="\n\n")
print(df.loc[2], end="\n\n")
print(df.loc[0:2], end="\n\n")

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23
3    23             32    34               76
4    43             73    23               67

   Math  C_programming  Java  Web_programming
2    34             25    67               23
3    23             32    34               76

Math               90
C_programming      70
Java               50
Web_programming    55
Name: 0, dtype: int64

Math               34
C_programming      25
Java               67
Web_programming    23
Name: 2, dtype: int64

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23

In [36]:
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a', 'b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a', 'b'])
df = df.append(df2)
print(df)

   a  b
0  1  2
1  3  4
0  5  6
1  7  8

### Exercise: use append to add the following table to table studentDF that you have created in the previous exercise. Note that we need the index of 5 and 6 for the new rows

In [49]:
d = {"Math" : [49, 41],
     "C_programming" : [37, 34],
     "Java" : [84, 73],
     "Web_programming" : [82, 55]}
new_df = pd.DataFrame(d, index=[5, 6])
new_df

   Math  C_programming  Java  Web_programming
5    49             37    84               82
6    41             34    73               55

In [54]:
appended_df = student_df.append(new_df)
appended_df

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23
3    23             32    34               76
4    43             73    23               67
5    49             37    84               82
6    41             34    73               55

### Exercise: use drop function to remove the last row from table studentDF

In [55]:
appended_df

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23
3    23             32    34               76
4    43             73    23               67
5    49             37    84               82
6    41             34    73               55

In [60]:
dropped_df = appended_df.drop(len(appended_df)-1)
dropped_df

   Math  C_programming  Java  Web_programming
0    90             70    50               55
1    10             20    41               66
2    34             25    67               23
3    23             32    34               76
4    43             73    23               67
5    49             37    84               82

## Descriptive Statistics

In [59]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],
'Age':[28,34,29,42]}
df = pd.DataFrame(data)
df.sum()

Name    TomJackSteveRicky
Age                   133
dtype: object

### Exercise: try to apply sum() with table studentDF. What is the result?

In [62]:
dropped_df.sum()

Math               249
C_programming      257
Java               299
Web_programming    369
dtype: int64

### Exercise: try to use axis attribute to change the orientation of the summation

In [63]:
dropped_df.sum(axis=1)

0    265
1    137
2    149
3    165
4    206
5    252
dtype: int64

### Exercise: use the above statistical functions on table studentDF, and see the results.

In [64]:
dropped_df.cumprod()

         Math  C_programming        Java  Web_programming
0          90             70          50               55
1         900           1400        2050             3630
2       30600          35000      137350            83490
3      703800        1120000     4669900          6345240
4    30263400       81760000   107407700        425131080
5  1482906600     3025120000  9022246800      34860748560

In [65]:
dropped_df.cumprod(axis=1)

   Math  C_programming    Java  Web_programming
0    90           6300  315000         17325000
1    10            200    8200           541200
2    34            850   56950          1309850
3    23            736   25024          1901824
4    43           3139   72197          4837199
5    49           1813  152292         12487944

In [66]:
#Create a Dictionary of series
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
'Lee','David','Gasper','Betina','Andres']),
'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}
#Create a DataFrame
df = pd.DataFrame(d)
df.describe()

             Age     Rating
count  12.000000  12.000000
mean   31.833333   3.743333
std     9.232682   0.661628
min    23.000000   2.560000
25%    25.000000   3.230000
50%    29.500000   3.790000
75%    35.500000   4.132500
max    51.000000   4.800000

### Exercise: use describe() on table studentDF and answer the following questions

In [78]:
des = dropped_df.describe()
des

            Math  C_programming       Java  Web_programming
count   6.000000       6.000000   6.000000         6.000000
mean   41.500000      42.833333  49.833333        61.500000
std    27.573538      22.973173  22.409076        21.002381
min    10.000000      20.000000  23.000000        23.000000
25%    25.750000      26.750000  35.750000        57.750000
50%    38.500000      34.500000  45.500000        66.500000
75%    47.500000      61.750000  62.750000        73.750000
max    90.000000      73.000000  84.000000        82.000000

In [79]:
des.loc["mean", "Math"]

41.5

In [80]:
des.loc["75%", "Java"]

62.75

In [81]:
des.loc["std", "Web_programming"]

21.002380817421628

## Missing Data

In [82]:
reindexed_df = dropped_df.reindex([0,1,2,3,4,5,6,7])
reindexed_df

   Math  C_programming  Java  Web_programming
0  90.0           70.0  50.0             55.0
1  10.0           20.0  41.0             66.0
2  34.0           25.0  67.0             23.0
3  23.0           32.0  34.0             76.0
4  43.0           73.0  23.0             67.0
5  49.0           37.0  84.0             82.0
6   NaN            NaN   NaN              NaN
7   NaN            NaN   NaN              NaN

## Check for Missing Values

In [91]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e','f','h'],columns=['one', 'two', 'three'])
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
print(df['one'].isnull(), end="\n\n")
print(df['two'].notnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: two, dtype: bool

### Exercise: use isnull() and notnull() with table studentDF and see the results.

In [93]:
reindexed_df.isnull()

    Math  C_programming   Java  Web_programming
0  False          False  False            False
1  False          False  False            False
2  False          False  False            False
3  False          False  False            False
4  False          False  False            False
5  False          False  False            False
6   True           True   True             True
7   True           True   True             True

In [94]:
reindexed_df.notnull()

    Math  C_programming   Java  Web_programming
0   True           True   True             True
1   True           True   True             True
2   True           True   True             True
3   True           True   True             True
4   True           True   True             True
5   True           True   True             True
6  False          False  False            False
7  False          False  False            False

## Filling Missing Data

In [98]:
s1 = reindexed_df.copy()
s2 = reindexed_df.copy()
s1 = s1.fillna(0)
s2 = s2.fillna(method='pad')
print(s1, end="\n\n")
print(s2)

   Math  C_programming  Java  Web_programming
0  90.0           70.0  50.0             55.0
1  10.0           20.0  41.0             66.0
2  34.0           25.0  67.0             23.0
3  23.0           32.0  34.0             76.0
4  43.0           73.0  23.0             67.0
5  49.0           37.0  84.0             82.0
6   0.0            0.0   0.0              0.0
7   0.0            0.0   0.0              0.0

   Math  C_programming  Java  Web_programming
0  90.0           70.0  50.0             55.0
1  10.0           20.0  41.0             66.0
2  34.0           25.0  67.0             23.0
3  23.0           32.0  34.0             76.0
4  43.0           73.0  23.0             67.0
5  49.0           37.0  84.0             82.0
6  49.0           37.0  84.0             82.0
7  49.0           37.0  84.0             82.0

### Exercise: What is the differences between s1 and s2.

s1's nan filled with constant value provided. In this case 0.

s2's nan filled with the value before itself. (Ref https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html?highlight=fillna#pandas.DataFrame.fillna)

## Joining/Grouping

In [100]:
left = pd.DataFrame({
'id':[1,2,3,4,5],
'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
'subject_id':['sub1','sub2','sub4','sub6','sub5']})

right = pd.DataFrame(
{'id':[1,2,3,4,5],
'subject_name':['Math','English',
'Social Science','Programming','Physics']})

print(left, end="\n\n")
print(right)

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

   id    subject_name
0   1            Math
1   2         English
2   3  Social Science
3   4     Programming
4   5         Physics

In [103]:
merged_table = pd.merge(left,right,on='id')
merged_table

   id    Name subject_id    subject_name
0   1    Alex       sub1            Math
1   2     Amy       sub2         English
2   3   Allen       sub4  Social Science
3   4   Alice       sub6     Programming
4   5  Ayoung       sub5         Physics

### Exercise: create table section and create table student as the following. You have to use merge() to join the section table with the student table below and name your table as score. Note that use id as a joining key

In [108]:
d = {"id" : [0, 1, 2, 3, 4, 5],
     "section" : ["one", "one", "one", "two", "two", "two"]}
left = pd.DataFrame(d)

d = {"id" : [0, 1, 2, 3, 4, 5],
     "name" : ["Mat", "Mike", "John", "Peecha", "Prabu", "Bunchu"],
     "math" : [34, 12, 34, 12, 65, 23],
     "english" : [23, 13, 51, 62, 12, 42]
    }
right = pd.DataFrame(d)
score = pd.merge(left, right, on="id")
score

   id section    name  math  english
0   0     one     Mat    34       23
1   1     one    Mike    12       13
2   2     one    John    34       51
3   3     two  Peecha    12       62
4   4     two   Prabu    65       12
5   5     two  Bunchu    23       42

### What is the result from using sum() on the groupby table?

In [111]:
score_sec = score.groupby('section')
score_sec.sum()

         id  math  english
section
one       3    80       87
two      12   100      116